services:
  - type: web
    name: carbonvault-api
    runtime: python
    rootDir: Backend
    buildCommand: pip install -r requirements.txt && (git rev-parse HEAD > COMMIT_HASH || true)
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAZORPAY_KEY_ID
        value: rzp_test_TkjH0Xr16eIeed
      - key: RAZORPAY_KEY_SECRET
        value: mc1c7MG2tjpbJFMRWxTa4kFq
      - key: CORS_ORIGINS
        value: https://final-carbon-vault.vercel.app,http://localhost:5173,http://127.0.0.1:5173
      - key: DEBUG
        value: "False"
